version: "3.7"

services:
  "bucai-lattice":
    image: ccr.ccs.tencentyun.com/bucai/lattice
    build: .
    restart: always
    networks:
      - bucai-network

networks:
  bucai-network:
    external: true